### ISSUE TITLE
Install/Download Docker package on Nano Server

### ISSUE THREAD

**Issue by yorickdocter** [OneGet/MicrosoftDockerProvider#11]
Downloading or installing the DockerMsftProvider results in the following error:
`WARNING: Cannot find path 'C:\Users\ADMINI~1\AppData\Local\Temp\DockerMsftProvider\DockerDefault_DockerSearchIndex.json' because it does not exist.
WARNING: Save-HTTPItem: Bits Transfer failed. Job State:  ExitCode = -2147023651
Save-Package : No match was found for the specified search criteria and package name 'Docker'. Try Get-PackageSource to see all available registered package sources.
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...ets.SavePackage:SavePackage) [Save-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.SavePackage`

Any tips on what's going wrong here?

**Comment by jayshah-msft** [comment]
@yorickdocter  are you behind a proxy? Or are you trying PowerShell Direct, or SSH remoting? If so this is a known issue: BITs API doesn't work on either of these remoting. If you can please try WinRM based Powershell Remoting, this provider should be working for you. Let me know if you are facing any further issues.
Thank you for your patience.

Cheers,
Jay!

**Comment by yorickdocter** [comment]
Was using PowerShell direct, connected to the IP did the trick. Thanks!

**Comment by rs38** [comment]
@jayshah-msft any idea why such an error occurs when using PS direct? should the bug be routed to the PS or hyper-v team?

**Comment by jayshah-msft** [comment]
@rs38 
This is a BITs issue. BITs team has been notified of this and they are working towards it.
