### ISSUE TITLE
Finding packages shows nothing but warnings

### ISSUE THREAD

**Issue by mterwoord** [OneGet/MicrosoftDockerProvider#12]
When I run ```Find-Package –providerName DockerMsftProvider``` all I see are 2 warnings:

```
WARNING: Cannot find path 'C:\Users\ADMINI~1\AppData\Local\Temp\DockerMsftProvider\DockerDefault_DockerSearchIndex.json' because it does not exist.
WARNING: Save-HTTPItem: Bits Transfer failed. Job State:  ExitCode = -2147023651
```

What am I doing wrong?

**Comment by jayshah-msft** [comment]
@mterwoord,
This could be same as https://github.com/OneGet/MicrosoftDockerProvider/issues/11
Let me know if that doesn't solve your issue.

Cheers,
Jay!

**Comment by mterwoord** [comment]
It seems related. I am using powershell direct. Maybe its possible to have the provider notify that?
(or mention it smewhere else, easily found)

**Comment by mterwoord** [comment]
That did the trick. Thanks!

**Comment by jayshah-msft** [comment]
@mterwoord 
Added https://github.com/OneGet/MicrosoftDockerProvider/commit/b81f8869fb312607d482b7b00ffd64c79d32415f as per your recommendation.

Thank you for your feedback, patience and continued patronage.

Cheers,
Jay!
