### ISSUE TITLE
Use dockerd.exe --register-service

### ISSUE THREAD

**Issue by PatrickLang** [OneGet/MicrosoftDockerProvider#13]
dockerd.exe has code that will register the service with reasonable defaults. If more parameters, etc are changed later - using `--register-service` instead of `New-Service` will make sure they're applied as the Docker service is set up.

Here's an example of a change that would be good to pick up:
https://github.com/docker/docker/issues/27696

**Comment by PatrickLang** [comment]
ping @jayshah-msft

**Comment by daBONDi** [comment]
Still an issue on 18.03-ee-1 package

**Comment by PatrickLang** [comment]
Scripts in aks-engine and other places are working around this with `net start docker`. Since this is old with no action, I'm closing it.
