### ISSUE TITLE
Docker v1.13 is released -- Please upgrade

### ISSUE THREAD

**Issue by abergs** [OneGet/MicrosoftDockerProvider#16]

**Comment by StefanScherer** [comment]
@abergs You can update to 1.13.1 CS now.

**Comment by abergs** [comment]
Nice, could that be acknowledged in this repo (so that for newcomers that find this place via google, it's obvious when you last made changes/updated versions)?

**Comment by StefanScherer** [comment]
I also found out yesterday, that the README has a good overview and how to update https://github.com/OneGet/MicrosoftDockerProvider#update-docker

**Comment by abergs** [comment]
@StefanScherer I'm a bit confused. Because when i ran the one-get command to install Docker i received a pretty old version and figured this whole thing was outdated. It would be nice if the readme acknowledged this right at the top? With something like:

## Looking for the latest version docker (13.1), [see our upgrade guide](https://github.com/OneGet/MicrosoftDockerProvider#update-docker)

**Comment by abergs** [comment]
Added a pull request for what I complained about #20

**Comment by StefanScherer** [comment]
The previous version was 1.12 from October. And the new release is available only since a few days.

**Comment by abergs** [comment]
Oh yes @StefanScherer I think I had 1.13 (which has been available for a couple of weeks if I am not misstaken?) Might be misstaken here, I am completely green to Docker (and OneGet)
