### ISSUE TITLE
Updating the package should start Docker service again

### ISSUE THREAD

**Issue by StefanScherer** [OneGet/MicrosoftDockerProvider#17]
I did some update tests from 1.12 CS to 1.13.1 CS with

```powershell
Install-Package -Name docker -ProviderName DockerMsftProvider -MinimumVersion 1.13.1 -Force
```

But afterwards the Docker service [isn't running](https://ci.appveyor.com/project/StefanScherer/dockerfiles-windows/build/1.0.239) and so the upcoming docker commands fail. I have expected that the Docker service is running after the update.

**Comment by sixeyed** [comment]
Agreed. After updating you need to run:

```
Set-Service docker -StartupType Automatic
Start-Service docker
```

- which is unexpected if the previous version was set to Automatic.

Ideally the update should check the current startup type before upgrading, and set the new version to the same.

**Comment by StefanScherer** [comment]
The recommended provider DockerProvider does restart automatically.
