### ISSUE TITLE
Don't support `http`

### ISSUE THREAD

**Issue by friism** [OneGet/MicrosoftDockerProvider#2]
It appears from this that http is supported, that should probably not be the case: https://github.com/friism/MicrosoftDockerProvider/blob/developer/0.1.0.0/MicrosoftDockerProvider.psm1#L88

**Comment by KrishnaV-MSFT** [comment]
@friism Thanks for the comment. We look into this and make an update.

**Comment by jayshah-msft** [comment]
This is done.
