### ISSUE TITLE
Support Windows 10

### ISSUE THREAD

**Issue by StefanScherer** [OneGet/MicrosoftDockerProvider#7]
Running the installer on Windows 10 Pro AU I get an error. So this package should support Windows 10 users to get the Windows Docker engine (eg. the open source version) up and running.

```
PS C:\ Install-Module -Name DockerMsftProvider -Repository PSGallery -Force

NuGet provider is required to continue
PowerShellGet requires NuGet provider version '2.8.5.201' or newer to interact with NuGet-based
repositories. The NuGet provider must be available in 'C:\Program
Files\PackageManagement\ProviderAssemblies' or
'C:\Users\vagrant\AppData\Local\PackageManagement\ProviderAssemblies'. You can also install the NuGet
provider by running 'Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force'. Do you want
 PowerShellGet to install and import the NuGet provider now?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"):
```

```
PS C:\> Install-Package -Name docker -ProviderName DockerMsftProvider

The package(s) come(s) from a package source that is not marked as trusted.
Are you sure you want to install software from 'DockerDefault'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): y
Install-Package : The term 'Get-WindowsFeature' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At line:1 char:1
+ Install-Package -Name docker -ProviderName DockerMsftProvider
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [In
   stall-Package], Exception
    + FullyQualifiedErrorId : FailedToDownload,Install-Package,Microsoft.PowerShell.PackageManagement.
   Cmdlets.InstallPackage
```

**Comment by PatrickLang** [comment]
`Get-WindowsOptionalFeature` would need to be used instead on Windows 10 if support is added to this provider later.

**Comment by PatrickLang** [comment]
Also, this should use Docker v1.13-dev, and v1.13 once it's released. v1.12 has some bugs on Windows 10

**Comment by StefanScherer** [comment]
Docker for Windows Beta 1.12.3-rc1-beta29 (8202) still installs the CS version of dockerd.exe

```
PS C:\Users\vagrant> docker version
Client:
 Version:      1.12.3-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bad4d12
 Built:        Tue Oct 25 08:19:41 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
```

What is the plan for Windows 10 once 1.13 it's released?
Using the 1.13 CS version or the 1.13 open source binaries?

**Comment by PatrickLang** [comment]
@friism any feedback?

**Comment by rs38** [comment]
cs = closed source?

**Comment by StefanScherer** [comment]
cs = commerial support :-)

**Comment by friism** [comment]
@StefanScherer I'm not opposed to having this work on Windows 10, but I think it's better to steer people towards Docker for Windows.

Shipping CS engine on Windows 10 is not ideal, but it was the best thing we could come up with in the release crunch. The plans are not finalized, but my hope is to use open sourced based releases with Docker for Windows on Windows 10 for the 1.13 release train. If that happens, I hope those builds will also be available through this installer.

**Comment by rs38** [comment]
DfW is fat! And the GUI makes people get wrong assumptions of the complexity of containers.
It brings many Features that are not optional. It was very slow on my system too..and the switch to windows docker never worked. I am pretty sure, I wont give it a third or forth try in the next months...

**Comment by StefanScherer** [comment]
Closing this as for Windows 10 there is Docker 1.13.1 available with D4W as well as direct download from get.docker.com. No need to use the CS version on Windows 10.
