### ISSUE TITLE
Update docker engine version (actual version is 19.03.11)

### ISSUE THREAD

**Issue by bbqrob** [OneGet/MicrosoftDockerProvider#72]
Is it possible to use the latest docker engine using this provider? Latest version is `v19.03.11` according to [this](https://github.com/docker/docker-ce/releases).

**Comment by andyfisher100** [comment]
Who are the project owners for this? It's getting massively out of date. 19.03.5 was released back in November 2019 and there are loads of bug fixes for windows containers since

@cwilhit @jayshah-msft Can you guys help?

**Comment by james-nesbitt** [comment]
I am starting to look at this now.  I am just trying to discover what needs to change.

FYI: I am on the Mirantis side, working on Docker-EE

**Comment by james-nesbitt** [comment]
Quick update:

1. I've isolated the docker/mirantis CI processes which are needed for this.  They are usable to process and update, but we will likely need to change out some signing key/certs (current docker cert expires 2021, so we may use it as it atm)
2. I have had little success fining the correct MS partner rep for changes to be made on the MS side, however I still have some leads that I am following up with.  If anybody on the MS side reads this that can help, please contact me.

**Comment by jsturtevant** [comment]
@cwilhit are you able to help here?

**Comment by cwilhit** [comment]
James and I are chatting offline and investigating.

**Comment by gerritsen** [comment]
@james-nesbitt and @cwilhit Hope you can fix this soon. It would be nice to have the latest docker version to check if the stability has improved. Thanx for your work! Do you know of an alternative way to get and install the latest docker release for windows server 2019?

**Comment by james-nesbitt** [comment]
@gerritsen you might try the incoming install replacements:  https://docs.mirantis.com/docker-enterprise/v3.1/dockeree-products/docker-engine-enterprise/dee-windows.html

My understanding is that OneGet is not the long term support path for containers on windows (I am not an authority on the topic, just a guy with a wrench)

**Comment by gerritsen** [comment]
> @james-nesbitt and @cwilhit Hope you can fix this soon. It would be nice to have the latest docker version to check if the stability has improved. Thanx for your work! Do you know of an alternative way to get and install the latest docker release for windows server 2019?

Thank you for that info! This will help us greatly.

**Comment by gerritsen** [comment]
> @gerritsen you might try the incoming install replacements: https://docs.mirantis.com/docker-enterprise/v3.1/dockeree-products/docker-engine-enterprise/dee-windows.html
> 
> My understanding is that OneGet is not the long term support path for containers on windows (I am not an authority on the topic, just a guy with a wrench)

Thank you for this info. It will help us greatly!

**Comment by thecloudtaylor** [comment]
We are intending to continue using OneGet for the Docker Engine installation as the pattern has been established and customers, automation and process already use it. For new software other approaches will likely be used.

**Comment by james-nesbitt** [comment]
In discussion with Microsoft, it is my intention to get proper refactoring of the implementation - new signing certs and corrected infra ownership of storage, so that OneGet can be supported in the long run.

In discussion we are targeting correct delivery of the next patch release (1st week of August.)  This should allow earlier missed release to also be installed.

**Comment by hoerup** [comment]
I'm not sure if this is the right place to post this, but i just updated to 19.03.11 via` install-package docker -providername DockerMSFTProvider -Update` - so far so good.

But the old version was reported as 
```
Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.5
```

but the new is 
```
Server: Docker Engine - Enterprise (Unlicensed - not for production workloads)
 Engine:
  Version:          19.03.11
```
If i downgrade to 19.03.8  - there's no note regarding unlicensed
```
Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.8
```

**Comment by james-nesbitt** [comment]
Interesting. I didn't expect that the fix was live yet.  With regards to the unlicensed comment, that is in discussion right now and is to be addressed on the Mirantis/Docker side (but please note that I am not an authority on this topic)

On the Mirantis/Docker side we did get updates into the one-get manifest, which was passed to MSFT, but I didn't think it would be reflected in OneGet yet as the location of the manifest is different right now, and we are still negotiating updating the processes to reflect that.

Note that a new patch release is heading out the door soon, so I'll get that updated again (not automated yet until we get confirmation from MSFT that we are good)

**Comment by james-nesbitt** [comment]
A follow up on the `Unlicensed` label in the engine version - I have been told that this has already been addressed for versions 19.03.12/18.09.13 for Windows. When we get the oneget update for those versions, there will be no such declaration.

**Comment by james-nesbitt** [comment]
We have update the one-get manifest for docker to the 19.03.12/18.09.13 versions, so they may be available when the update is read by OneGet.

**Comment by bbqrob** [comment]
Great, works fine now.

**Comment by tfenster** [comment]
Does it? I just now updated and still see 
```
Server: Docker Engine - Enterprise (Unlicensed - not for production workloads)
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.13.11
  Git commit:       0da829ac52
  Built:            06/26/2020 17:19:32
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Comment by tfenster** [comment]
Just to confirm, for whatever reason it took a couple of weeks for me, but now it also works:

```
Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.13.13
  Git commit:       f295753ffd
  Built:            08/05/2020 19:26:41
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Comment by james-nesbitt** [comment]
Old issue, but just for peace of mind - we update the manifest for docker 20.10.0 yesterday, so that should show up.
