### ISSUE TITLE
DockerMsftIndex.json shows "null" instead of "19.03" - cannot download zip archive

### ISSUE THREAD

**Issue by dmpe** [OneGet/MicrosoftDockerProvider#74]
https://dockermsft.blob.core.windows.net/dockercontainer/DockerMsftIndex.json

Since today, when I am trying to download latest version of docker for windows via curl and jq, I get following from the above json file. 
```
{
"channels": {
"cs": {
"alias": null
},
```

The alias has been however a different one, i.e. it showed "19.03" - instead of `null`

@cwilhit can you please take a look into it, i.e. why it is now `null`?
Thanks.

**Comment by andyfisher100** [comment]
Not sure if this is related but if i run the powershell command i get two warnings i never used to get

```
PS C:\Windows\system32> Install-Package -Name docker -ProviderName DockerMsftProvider -Force
WARNING: The property 'version' cannot be found on this object. Verify that the property exists.
WARNING: The property 'Properties' cannot be found on this object. Verify that the property exists.
```

**Comment by dmpe** [comment]
This has been now fixed...
