### ISSUE TITLE
Update docker engine version

### ISSUE THREAD

**Issue by esrahofstede** [OneGet/MicrosoftDockerProvider#76]
We are using the [https://download.docker.com/components/engine/windows-server/index.json](https://download.docker.com/components/engine/windows-server/index.json) link to download the latest docker.exe file.

The latest version in this json file is 19.03.5 and contains the dowload link [https://download.docker.com/components/engine/windows-server/19.03/docker-19.03.5.zip](https://download.docker.com/components/engine/windows-server/19.03/docker-19.03.5.zip).

This issue seems related to #72, where the most recent version was also 19.03.05.

Can this json file be updated to the most recent version?

**Comment by StefanScherer** [comment]
Hey @esrahofstede 
The link that you are using is no longer maintained. Docker Engine EE is no longer part of download.docker.com.

You should update your link and use the one that is used in line 21 https://github.com/OneGet/MicrosoftDockerProvider/blob/master/DockerMsftProvider.psm1#L21
That gives you 19.03.11 at the moment.

**Comment by esrahofstede** [comment]
@StefanScherer thanks for the update.
Closed the issue
