### ISSUE TITLE
DockerUrl expired

### ISSUE THREAD

**Issue by JPaja** [OneGet/MicrosoftDockerProvider#90]
https://github.com/OneGet/MicrosoftDockerProvider/blob/a70c037cd153b8277e2f2d85224d05a044225ad4/DockerMsftProvider.psm1#LL21C2-L21C2

dockerURL: https://go.microsoft.com/fwlink/?LinkID=825636&clcid=0x409 now resolves to https://www.microsoft.com/404

Which fails 
```ps1
Install-Package -Name docker -ProviderName DockerMsftProvider -Force -Verbose
```
```
VERBOSE: Downloading https://www.microsoft.com/404 to
AppData\Local\Temp\DockerMsftProvider\DockerDefault_DockerSearchIndex.json
WARNING: The remote server returned an error: (404) Not Found.
```

**Comment by AlexanderAvazkhodjayev** [comment]
I am getting the same issue, how come the page went down

**Comment by JPaja** [comment]
URL now points to correct address
