### ISSUE TITLE
Installing docker through the DockerMsftProvider broken?

### ISSUE THREAD

**Issue by Thomastouma** [OneGet/MicrosoftDockerProvider#91]
DockerMsftProvider v1.0.0.8
Server: 2022-datacenter-azure-edition
Proxy: False
tls12: True

Recently our packer builds started failing out of nowhere when installing docker. We are not behind a proxy and our powershell sessions are tls 12 and i've seen other open issues regarding this problem with possible fixes that are applicable if you are behind a proxy or if you are not enforcing tls12.  I FANCY some more light shed on this problem as it indeed to me atleast seem to be something wrong on your end and not ours as users.

Code:
`Install-Module -Name DockerMsftProvider -Repository PSGallery -Force`
`Install-Package Docker -ProviderName DockerMsftProvider -Force`

Error message: 
Cannot find path 'C:\Windows\TEMP\DockerMsftProvider\DockerDefault_DockerSearchIndex.json' because it does not exist.
Cannot bind argument to parameter 'downloadURL' because it is an empty string.
The property 'AbsoluteUri' cannot be found on this object. Verify that the property exists.
The property 'RequestMessage' cannot be found on this object. Verify that the property exists.
Install-Package : No match was found for the specified search criteria and package name 'Docker'. Try Get-PackageSource to see all available registered package sources.

**Comment by amapi** [comment]
Help, exact same error here

**Comment by Mnbill** [comment]
Hello, i have the same issue.

**Comment by Judicael99** [comment]
same

**Comment by tsipsey** [comment]
Same. Running Get-PackageSource shows DockerMsftProvider source location as https://go.microsoft.com/fwlink/?LinkID=825636&clcid=0x409  which redirects to an unreachable location:  https://dockermsft.azureedge.net/dockercontainer/DockerMsftIndex.json

**Comment by thecloudtaylor** [comment]
As of May the Docker Provider has been removed. Alternative options are at https://learn.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=dockerce#windows-server-1

For more details on the depreciation see https://techcommunity.microsoft.com/t5/containers/reminder-updates-to-windows-container-runtime-support/ba-p/3620989 and https://techcommunity.microsoft.com/t5/containers/updates-to-the-windows-container-runtime-support/ba-p/2788799
